# Generated by Django 2.1.7 on 2019-03-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], default='PENDING', max_length=16),
        ),
    ]
